name: 'Build'
description: 'Builds project and uploads artifacts'
inputs:
  shell:
    require: true
    type: string
outputs:
  git_describe:
    value: ${{ steps.git-describe.outputs.git_describe }}


runs:
  using: "composite"
  steps:
    - id: git-describe
      shell: ${{inputs.shell}}
      run: |
        echo "git_describe=$(git describe --tags)" >> "$GITHUB_OUTPUT"
