name: 'Run tests'
description: 'Creates SDK and Uploads artifacts'
inputs:
  package-name:
    required: true
    type: string
  os:
    required: true
    type: string
  arch:
    required: true
    type: string

runs:
  using: "composite"
  steps:
    - uses: actions/download-artifact@v3
      shell: ${{inputs.shell}}
      with:
        name: ${{inputs.package-name}}-${{inputs.os}}-${{inputs.arch}}
        path: |
          cmbuild
    - name: Run test suite
      shell: bash
      run: |
        ci/${{inputs.os}}/test.sh
    - name: Upload Artifacts
      uses: actions/upload-artifact@v3
      with:
        name: testsuite-${{inputs.os}}-${{inputs.arch}}-logs
        path: |
          TestSuite/Verify3/*.log
          TestSuite/Logs*.txt
